version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    # Remove volume mapping for production container to prevent overrides
    # volumes:
    #   - /app/node_modules
    #   - .:/app
    environment:
      - NODE_ENV=production
      - DOCKER_CONTAINER=true
      - PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VECTOR_DB_URL=http://vector-db:6333
    restart: unless-stopped
    depends_on:
      - vector-db

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
      - '5173:5173'
    environment:
      - NODE_ENV=development
      - DOCKER_CONTAINER=true
      - PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VECTOR_DB_URL=http://vector-db:6333
    volumes:
      - /app/node_modules
      - /app/app/node_modules
      - ./app:/app/app
      - ./api:/app/api
      - ./server.js:/app/server.js
    command: npm run dev
    depends_on:
      - vector-db

  vector-db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always

volumes:
  qdrant_data:
