version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=production
      - DOCKER_CONTAINER=true
      - PORT=3001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - DOCKER_CONTAINER=true
      - PORT=3001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - /app/node_modules
      - ./app:/app/app
      - ./api:/app/api
      - ./server.js:/app/server.js
    command: npm run dev
