services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '3000:3000'  # Keep production app on port 3000
        volumes:
            - /app/node_modules
            - .:/app
        environment:
            - NODE_ENV=production
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        restart: unless-stopped

    # Development configuration
    dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '3001:3000'  # Map dev container's 3000 port to host's 3001
        environment:
            - NODE_ENV=development
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        volumes:
            - ./app:/app/app
            - ./api:/app/api
            - ./server.js:/app/server.js
            - /app/node_modules
        command: npm run dev
