version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"  # Map to standard HTTP port
    environment:
      - NODE_ENV=production
      - QDRANT_URL=http://qdrant:6333
      - DOCKER_CONTAINER=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - qdrant
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - portfolio_network
    dns:
      - 8.8.8.8  # Use Google DNS as fallback
    # Health check to ensure container is working properly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT_ALLOW_CORS=true
    restart: unless-stopped
    networks:
      - portfolio_network
    # Make sure Qdrant stays healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  qdrant_data:

# Define an explicit network to ensure container communication
networks:
  portfolio_network:
    driver: bridge
