version: '3.8'

services:
  # Development version of the application
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  # API
      - "5173:5173"  # Vite dev server
    environment:
      - NODE_ENV=development
      - QDRANT_URL=http://qdrant:6333
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      # Mount source code for hot reloading
      - ./:/app
      # Prevent node_modules from being overwritten by host
      - /app/node_modules
      - /app/api/node_modules
      - /app/app/node_modules
    depends_on:
      - qdrant
    command: npm run dev:cloud

  # Qdrant vector database - same as production but with different ports
  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_dev_data:/qdrant/storage
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # GRPC API
    environment:
      - QDRANT_ALLOW_CORS=true

volumes:
  qdrant_dev_data:
