name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      # Create .env.production file with environment variables
      - name: Setup Environment Variables
        run: |
          echo "Creating production environment variables"
          echo "VITE_NODE_ENV=production" > app/.env.production
          echo "VITE_API_URL=/api/askGPT" >> app/.env.production
          cat app/.env.production
      
      # Add health check step that verifies the API endpoint after deployment
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_FIELD_0BAAFF90F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "app"
          api_location: "api" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          app_build_command: "npm run build" # Explicitly use our custom build command
          ###### End of Repository/Build Configurations ######
          
      # Verify API endpoint after deployment
      - name: Verify Azure Function
        if: success()
        run: |
          echo "Verifying API endpoint..."
          # Allow some time for function to be fully deployed
          sleep 30
          # Try multiple times in case of initial startup delay
          for i in {1..3}; do
            response=$(curl -s -o /dev/null -w "%{http_code}" https://happy-field-0baaff90f.azurestaticapps.net/api/askGPT -X OPTIONS)
            if [ "$response" -eq 200 ] || [ "$response" -eq 204 ]; then
              echo "API endpoint verified successfully!"
              exit 0
            fi
            echo "Attempt $i: API verification returned status $response, retrying after 10s..."
            sleep 10
          done
          echo "API verification failed after 3 attempts"
          # Don't fail the workflow on API verification failure
          # This is just a health check, not a blocker

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_FIELD_0BAAFF90F }}
          action: "close"
          app_location: "app"
          api_location: "api"
          output_location: "dist"
