name: Debug and Test API

on:
  # Manual trigger
  workflow_dispatch:

jobs:
  deploy_test_endpoints:
    runs-on: ubuntu-latest
    name: Deploy API Test Endpoints
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_FIELD_0BAAFF90F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "app"
          api_location: "api"
          output_location: "dist"
          
      - name: API Health Check
        run: |
          echo "Verifying API endpoints..."
          # Allow time for deployment to complete
          sleep 60
          
          # Test regular API endpoint
          echo "Testing askGPT endpoint..."
          askgpt_response=$(curl -s -o /dev/null -w "%{http_code}" https://drewclark.io/api/askGPT -X GET)
          echo "askGPT status: $askgpt_response"
          
          # Test diagnostic API endpoint
          echo "Testing apiTest endpoint..."
          apitest_response=$(curl -s -o /dev/null -w "%{http_code}" https://drewclark.io/api/apiTest -X GET)
          echo "apiTest status: $apitest_response"
          
          # Print detailed information if available
          if [ "$apitest_response" -eq 200 ]; then
            echo "API Test endpoint response:"
            curl -s https://drewclark.io/api/apiTest | jq .
          fi
