name: CI/CD Pipeline

on: [push, pull_request]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Install Docker Compose
              run: |
                  sudo apt-get update
                  sudo apt-get install -y docker-compose

            - name: Build and test
              run: |
                  docker-compose -f docker-compose.yml -f docker-compose.test.yml build
                  docker-compose -f docker-compose.yml -f docker-compose.test.yml run app npm test

            # (Optional) Log in to Docker Hub
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            # Build and push your Docker image to Docker Hub
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .  # Use local context instead of Git URL
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:latest
