name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and test
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.test.yml build
          docker-compose -f docker-compose.yml -f docker-compose.test.yml run app npm test

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Using Node 18 to match Dockerfile
          
      - name: Install dependencies
        run: npm install
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: aiandrew631/portfolio:latest,aiandrew631/portfolio:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
