name: Build and Deploy to Droplet

on:
  push:
    branches:
      - main

env:
  # Define environment variables that can be reused
  DOCKER_IMAGE: aiandrew631/portfolio:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: aiandrew631/portfolio:latest
          build-args: 
            VITE_API_URL: ${{ secrets.VITE_API_URL }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Creating .env file on droplet..."
            cat > /home/${{ secrets.DEPLOY_USER }}/.env <<'EOF'
            NODE_ENV=${{ secrets.NODE_ENV }}
            ADMIN_ACCESS_TOKEN=${{ secrets.ADMIN_ACCESS_TOKEN }}
            DOCKER_CONTAINER=true
            PORT=3000
            VITE_API_URL=${{ secrets.VITE_API_URL }}
            # add more environment variables as needed
            EOF
            echo "Pulling the latest image from Docker Hub..."
            docker pull aiandrew631/portfolio:latest
            echo "Stopping and removing old container (if exists)..."
            docker stop portfolio || true
            docker rm portfolio || true
            echo "Starting new container with .env file..."
            docker run -d --name portfolio --env-file /home/${{ secrets.DEPLOY_USER }}/.env -p 80:3000 aiandrew631/portfolio:latest
