name: Trigger auto deployment for landingpage

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/landingpage-AutoDeployTrigger-ea4b4ab4-599d-441e-8b2d-aa04f3ba2814.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.LANDINGPAGE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LANDINGPAGE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LANDINGPAGE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        id: build_and_push
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: docker.io
          registryUsername: ${{ secrets.LANDINGPAGE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LANDINGPAGE_REGISTRY_PASSWORD }}
          containerAppName: landingpage
          resourceGroup: portfolio-apps
          imageToBuild: aiandrew631/landingpage:${{ github.sha }}
          buildArguments: |
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        continue-on-error: true
        
      # Add environment variables to Container App regardless of build outcome
      - name: Set OpenAI API key in Container App
        run: |
          # Add environment variables to Container App (as a secret)
          az containerapp secret set -n landingpage -g portfolio-apps --secrets openai-api-key=${{ secrets.OPENAI_API_KEY }}
          az containerapp update -n landingpage -g portfolio-apps --set-env-vars "OPENAI_API_KEY=secretref:openai-api-key"

      - name: Set up retry deployment script
        if: steps.build_and_push.outcome == 'failure'
        run: |
          chmod +x .github/scripts/deploy-with-retry.sh
          
      - name: Deploy with retry logic
        if: steps.build_and_push.outcome == 'failure'
        run: |
          # Set Container App registry credentials
          az containerapp registry set -n landingpage -g portfolio-apps --server docker.io --username ${{ secrets.LANDINGPAGE_REGISTRY_USERNAME }} --password ${{ secrets.LANDINGPAGE_REGISTRY_PASSWORD }}
          
          # Run the retry script
          .github/scripts/deploy-with-retry.sh landingpage portfolio-apps aiandrew631/landingpage:${{ github.sha }}
