name: Trigger auto deployment for portfolio

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/portfolio-AutoDeployTrigger-0f753666-4c11-4661-80d5-ba4c535f0179.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PORTFOLIO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PORTFOLIO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PORTFOLIO_AZURE_SUBSCRIPTION_ID }}
          
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Using Node 18 to match Dockerfile
          
      - name: Install dependencies
        run: npm install

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: docker.io
          registryUsername: ${{ secrets.PORTFOLIO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PORTFOLIO_REGISTRY_PASSWORD }}
          containerAppName: portfolio
          resourceGroup: DefaultResourceGroup-EUS
          imageToBuild: aiandrew631/portfolio:latest
